### ISSUE TITLE
GPT2和GPT属于transformer类吗

### ISSUE THREAD

**Issue by Hiliuhui** [catqaq/OpenTextClassification#6]
![image](https://github.com/catqaq/OpenTextClassification/assets/44133517/09f34a73-de76-43c6-9e89-05a68784a2f4)

**Comment by catqaq** [comment]
属于呀，为了提供完整的示例，项目中提供了encoder-only(比如bert)、encoder-decoder（比如T5）和decoder-only模型（比如GPT）~
