### ISSUE TITLE
运行浅层机器学习方法，model = "GBDT"，出现如下问题。其他机器学习方法功能正常。

### ISSUE THREAD

**Issue by Hiliuhui** [catqaq/OpenTextClassification#7]
f"Invalid classes inferred from unique values of `y`.  "
ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0 1 2 3 4 5 6 7], got [ 0  2  3  5  6  7  9 11]

**Comment by Hiliuhui** [comment]
已经解决

**Comment by catqaq** [comment]
> 

你好，具体是什么原因呢？我刚大概搜了下似乎是xgboost版本的问题？
